### ISSUE TITLE
Limit measurement index to an organization's measurements

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#1028]
Users and admin for an organization should only be able to see their own measurements. Currently the measurement index action returns and displays all measurements.

### Criteria for Completion:
 - [ ] Update the Measurements controller index action to limit measurements to the current organization. Follow the existing pattern used in other controllers.
 - [ ] Add specs to confirm this new behavior.

**Comment by Nalisa8** [comment]
I would like to work on this ticket
