### ISSUE TITLE
User Should Be Able To Configure The Data They Are Collecting

### ISSUE THREAD

**Issue by Deanout** [rubyforgood/abalone#131]
The stakeholders should be able to configure the types of data they collect themselves. The use of a custom column will allow for multiple users to track what they need to track without developer intervention as well as without maintaining separate schemas. 

- [ ] Create The Custom Column Model
- [ ] Attach To ___ Model
- [ ] Create Mixin for custom columns
- [ ] Need Mixin Callback for dealing with undefineds

- [ ] Custom Columns should be [1:M]

**Comment by mike-a-yen** [comment]
![Screenshot from 2020-04-05 11-03-45](https://user-images.githubusercontent.com/12302641/78506254-3aaef680-772d-11ea-8f5f-c02084620b72.png)

**Comment by mdworken** [comment]
Closed via #132 and others
