### ISSUE TITLE
Change displayed banner to match organization of logged in user

### ISSUE THREAD

**Issue by RachelWyatt** [rubyforgood/abalone#135]
When I am logged in as a User with Organization "White Abalone", I should see the following home page banner:

<img width="1602" alt="Screen Shot 2020-04-18 at 11 05 18 AM" src="https://user-images.githubusercontent.com/37967627/79642220-342b7080-816a-11ea-91a6-dda47895ae26.png">

When I am logged in as a User with Organization "PInto Abalone", I should see the following home page banner:

![PSRF-new logo copy](https://user-images.githubusercontent.com/4042423/80844568-d19b9100-8bbb-11ea-822b-4fa521d3ad3f.jpg)

**Comment by RachelWyatt** [comment]
I've reached out to @corneliusellen about getting the source image for this, since I'm having trouble finding it.

**Comment by jtu0** [comment]
![PSRF-new logo copy](https://user-images.githubusercontent.com/4042423/80844568-d19b9100-8bbb-11ea-822b-4fa521d3ad3f.jpg)

Caitlin sent over this for us to use!  She also says she can get us photos of abalone if we want.

**Comment by benreyn** [comment]
This issue was superseded by #238 and that issue was closed in #292. I am going to close this issue for now, but we may circle back on something similar in the future.
