### ISSUE TITLE
Landing Page Redesign

### ISSUE THREAD

**Issue by RachelWyatt** [rubyforgood/abalone#136]
Right now, the landing page is tailored to White Abalone. Since we're trying to extend this to multiple labs, we should have a group-agnostic landing page for users who haven't logged in. Once someone logs in, they can see specific data for the organization they belong to.

- [ ] Landing page is generalized beyond white abalone
- [x] Landing page has easy-to-find login
- [x] No dynamic data displayed on landing page

**Comment by mdworken** [comment]
Hadad is taking this one!
