### ISSUE TITLE
Expand "operation" model to allow stateful actions on tanks/families

### ISSUE THREAD

**Issue by mdworken** [rubyforgood/abalone#139]
In order to record the movement of families to/from different tanks, we need to expand/modify our "Operation" model. Let's add attributes to it (or an inheriting sub-class) so that we can record the following actions:

1) Removing a family from a tank.
2) Placing a family in a tank.

**Acceptance criterion:**
- [x] Can remove a family from a tank (by creating a new operation)
- [x] Can add a family to a tank (by creating a new operation)
- [x] Unit + integration tests
- [ ] A deliberate approach to how we'd handle potential "Order of Operations" problems

**Extra credit**

- [ ] Similar, but for the "count" associated with the family/tank. (Will be scoped out more in another ticket later otherwise)

**Out of Scope**

1. Request/System specs
2. Using the CSV uploader

**Comment by jtu0** [comment]
@mdworken Can a family ever be split across multiple tanks?
Or will a family always be in the same tank together?

Similarly, can a tank have multiple families?

**Comment by jtu0** [comment]
- [ ] `Operation` doesn't automatically `.perform` - need to make that happen before closing this issue

**Comment by mdworken** [comment]
Closed via #148
