### ISSUE TITLE
Can we automatically delete merged branches?

### ISSUE THREAD

**Issue by zspencer** [rubyforgood/abalone#149]
When I was working on this project, the large number of merged-but-still-existing branches made it a bit noisy when trying to switch between the main pranch and the WIP branch I was building on.

There's [a handy-dandy setting which will automatically delete branches that are merged](https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches) that may help with this.

**Comment by jtu0** [comment]
Done, thank you!
