### ISSUE TITLE
Create configurable list of acceptable measurements within an Organization

### ISSUE THREAD

**Issue by mdworken** [rubyforgood/abalone#207]
Users will enter custom measurements through the measurements csv. To avoid issues with misspelled measurement values or inconsistent namings/capitalization, we would like to make an Organization-wide "accept list" (we're intentionally avoiding the equivalent term "whitelist") of acceptable measurements.

**Acceptance Criterion**
- [ ] Each organization can be configured to have it's own list of acceptable names for measurements.
- [ ] Seeds/factories modified to include an example with an accept list.

Example allowlist
 - Length (in inches or centimeters)
 - Quantity (estimated of family population)

 
Note: Handling the actual behavior of the accept list is out of scope for this ticket and will be addressed in #

**Comment by NickSchimek** [comment]
I'm still interested in doing this. Is it cool if I work on it?

**Comment by benreyn** [comment]
I think we actually got this resolved in #308 during the PHR event last week! Ill close this issue! Sorry for the confusion @NickSchimek
