### ISSUE TITLE
Fleshed out reporting interface

### ISSUE THREAD

**Issue by mdworken** [rubyforgood/abalone#240]

**Comment by benreyn** [comment]
@mdworken and I have discussed blazer as a potential solution for this, but scoping db access is a bit tricky. I am not confident that it can be done with blazer, but if it can, blazer will give us 99% of a drop in solution.

**Comment by benreyn** [comment]
Alernatively we may need to generate reports on an as needed basis as issues / PRs etc.

**Comment by benreyn** [comment]
@benreyn to make two tickets for this.

**Comment by benreyn** [comment]
Broke this out into the two types of reporting we will need (developer built and user built) in #335 and #337
