### ISSUE TITLE
Add a "Remove" link for any unsuccessful CSV uploads

### ISSUE THREAD

**Issue by mdworken** [rubyforgood/abalone#245]
Our users will probably upload a lot of invalid CSVs. Currently those failed jobs take up a lot of visual space on the `/file_uploads` page. To help them keep their space clean, let's add a "Remove" button for any FAILED uploads.

**Acceptance Criterion**
- [ ] Failed uploads can be removed by clicking a link/button
- [ ] Uploads that did NOT fail will not have a link/button, and cannot be removed

**Comment by benreyn** [comment]
As a reach goal here, we can also add a button to "Remove all failed csvs"

**Comment by mdworken** [comment]
Not a reach at all! Can you pull that into a separate ticket though?
