### ISSUE TITLE
Audit models for validations

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/abalone#248]
@benreyn or @mdworken to flesh this out. Need to take a pass at both database level contraints and model level validations. 

Probably would be helpful to chat with some stakeholders for this.

**Comment by NickSchimek** [comment]
While working on issue #242 we found that the processed_file and temporary_file relationship is currently optional. It might be a good idea to make this a required relationship for a couple reasons. 1. It seems that temporary_file may actually be permanent files, and 2: The download csv feature currently depends on the processed_file to belong to a temporary_file.

**Comment by mattwd7** [comment]
I'm happy to comb through all the models and add any missing validations & associated specs 👍

**Comment by CraigJZ** [comment]
Thanks @mattwd7!! I'll take a look at the PR soon.
