### ISSUE TITLE
Analytics - Backend (can be split into multiple issues) 

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#32]
Analytics:
- spawning history of the broodstock (i.e., when we attempted to spawn them, were they successful in releasing gametes)
- total egg, larval, or juvenile production by year (esp. how many year-old animals are produced annually)
- mortality within a cohort/population over time
- size distribution of animals within a population or within the entire captive breeding program
- average growth rates of tagged individuals within populations or size classes over time

**Comment by ThunderHeavyIndustries** [comment]
- mortality within a cohort/population over time

https://github.com/rubyforgood/abalone/blob/master/app/lib/aggregate_calculations.rb#L3

**Comment by ThunderHeavyIndustries** [comment]
- spawning history of the broodstock (i.e., when we attempted to spawn them, were they successful in releasing gametes)

https://github.com/rubyforgood/abalone/blob/initial_calculations/app/lib/aggregate_calculations.rb#L10

**Comment by ThunderHeavyIndustries** [comment]
- total number of animals in the program, by spawning date and holding facility
https://github.com/rubyforgood/abalone/blob/initial_calculations/app/lib/aggregate_calculations.rb#L5

**Comment by ThunderHeavyIndustries** [comment]
- size distribution of animals within a population or within the entire captive breeding program

https://github.com/rubyforgood/abalone/blob/initial_calculations/app/lib/aggregates.rb

**Comment by ThunderHeavyIndustries** [comment]
- average growth rates of tagged individuals within populations or size classes over time

**Done**
