### ISSUE TITLE
CSV upload for Cohorts

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/abalone#322]
As we onboard new organizations to our software, we will need a way for them to import their existing data in large batches. The best way to accomplish this is with a CSV upload. We should provide them with a page that allows them to...

- [ ] Download a CSV file that specifies the format that they should upload in
- [ ] Upload a CSV that matches this specified format
- [ ] Inform them of the status of this upload
  - completed (all records uploaded)
  - failed (some kind of error occured)
  - queue (has not started processing yet)
  - processing

This ticket encompasses only the CSV based upload for Cohort records.

We have some existing CSV upload infrastructure, but I wouldn't let that guide you too much on this issue, as that functionality was built for an earlier iteration of this application and may not longer be the best way to handle CSV based data-upload.

**Comment by NickSchimek** [comment]
I can start working on this

**Comment by CraigJZ** [comment]
Thanks @NickSchimek! I don't think we have updated this issue since changing `family` to `cohort`. The requirements in the original ticket still apply for cohort, though. The animal and enclosure imports should act as good examples for this one now. Let us know if you run into any questions.

**Comment by NickSchimek** [comment]
OK. Thanks for the info @CraigJZ . That is good to know.

**Comment by NickSchimek** [comment]
Sorry I've been terribly busy the past month, I'm getting back around to this, and am starting to work on it

**Comment by NickSchimek** [comment]
If there are validation errors for any record in the csv file. Should the entire upload fail, or should we persist the records that are free from errors?

**Comment by CraigJZ** [comment]
For the animal and enclosure imports we are saving the records that are free from errors and reporting on the ones that fail. If possible, it would be nice to follow that pattern here too.

From `ImportAnimalsJob`

```
begin
        status[:created_count] += 1 if Animal.create(attrs)
      rescue ActiveRecord::RecordNotUnique, ActiveRecord::RecordInvalid => e
        message = e.instance_of?(ActiveRecord::RecordNotUnique) ? :duplicate : :invalid
        status[:errors] << { tag: attrs[:tag], type: message }
        status[:error_count] += 1
      end
```

**Comment by NickSchimek** [comment]
Thanks @CraigJZ - Yes, that answers my question. I think prior to the Animal and Enclosure Import CSV implementations the previous import implementation would abort on failure so I wanted to double check.

On another note. I feel that the UI is a bit confusing after importing a file. For instance:
After Importing an Enclosure CSV the user is redirected to the enclosure index where there is a very quick flash message saying `processing file`. And then above the Enclosure header there is a persistent status message that says `processing file` - The status message never updates <- Is this just a me issue or is this what you see too?
In order for the user to know the status of the update the user needs to click on `Uploads` drop down and then select `CSV uploads`

It sounds like for this PR you want the status message to be updated dynamically, and then perhaps we can display a link with the status message when the status is complete to direct the user to the `CSV Uploads` index page. -> Does that sound about right? or should I implement the same way that it is currently implemented?

**Comment by NickSchimek** [comment]
Or perhaps after importing a csv the user should be redirected to the CSV Uploads index page?

**Comment by CraigJZ** [comment]
I agree on the current UI being confusing. The pattern you described of updating the status dynamically and providing a link over to the CSV Uploads index page is what we were thinking here.

**Comment by NickSchimek** [comment]
OK sounds good. I will take a look at implementing that. Let me know if you have a desired implementation in mind.

**Comment by CraigJZ** [comment]
Thanks! I think my only preference on implementation would be to avoid anything that introduces a lot of new complexity. We have stimulus installed, if that interests you. In the past, I've done file upload status updates with Action Cable, but I'm not sure we would want to introduce that into the app, given the redis requirement. If you think it might be better to brake the status piece out into a separate issue from the file upload, that would be cool too.

**Comment by NickSchimek** [comment]
Thank you for the detailed answer. I was thinking action cable, but it
sounds like it’s probably not the right time to do that. Stimulus does
interest me so I will look into going that route. If it becomes to big for
this issue then I will break it into another task. Thanks for the detailed
response.

**Comment by NickSchimek** [comment]
Creating a cohort only requires an organization. Are there any other validations that should be added at this time?

FYI: I will split this into two issues as we discussed. I would like to take on the issue of updating the status dynamically, but I may not be able to as I'm getting busier after the start of the year.

**Comment by CraigJZ** [comment]
I suspect we will want to add a validation for name, at some point. At this time, though, I think we should just stick with organization.

Sounds good. Thanks for working on this!! :)

**Comment by NickSchimek** [comment]
Perfect. I will get this done soon. Sorry it’s been taking so long

**Comment by NickSchimek** [comment]
Can I get a confirmation on what headers should be included for the cohort CSV import?
I believe we'll need the following fields:
 - name
 - female_tag
 - male_tag
 - enclosure
 - location

**Comment by CraigJZ** [comment]
@NickSchimek I'm sorry I missed this last week. I believe the location field can be left off but name, female_tag, male_tag and enclosure should all be included.

**Comment by NickSchimek** [comment]
In regards to `Animal tags`. It looks like a tag is not unique, well it is unique within the scope of a cohort. Is this correct?

If it is, then the import will create new corhorts and animals, it will associate cohorts to existing enclosures, and possibly create enclosures if an existing enclosure does not exist yet. <- I will proceed with this assumption - let me know if I'm incorrect.

**Comment by CraigJZ** [comment]
For #1 - Yes, the info we have, so far, shows that tags should be unique within the cohort. Yep, that assumption is correct.

For #2 - Thanks for catching this. I do think what you are describing is a hole in our current validations. I believe that location should be required on an enclosure and, in turn, a location should be unique within a facility. I'd like to get confirmation on that, though, before making those changes. Would it be feasible to proceed leaving location off and we will file an issue for the potential cohort to wrong enclosure bug here. What do you think?

In general, I expect that we will tighten up some of the validations as we begin working with the actual organization data.

**Comment by NickSchimek** [comment]
Perfect. I’m ok with that. Thank you!
