### ISSUE TITLE
Scope Animal to an Organization

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#333]
As we plan the multi-tenancy of the application, a Animal should belong to an Organization.

Acceptance Criteria

- [x] Add a belongs_to relationship on Animal
- [x] Add a has_many relationship on Organization
- [x] Add an organization_id column to Animal with an index
- [x] Update existing factory for Animal with an organization
- [x] Add specs to Organization and to Animal for the added relationship
- [x] Scope queries that occur on the `AnimalsController` to the current logged in users organization

**Comment by benreyn** [comment]
Worth noting that CRUD routes/actions already exist for the Animal model. These were built before we realized that much of the work to make the app fully multi-tenant was yet to be done. As a part of this task, or as a follow up task, the queries that occur on the `AnimalsController` should be scoped to the current logged in users organization.

**Comment by CraigJZ** [comment]
Thanks for noting that. I have added scoping the `AnimalsController` queries to the acceptance criteria.
