### ISSUE TITLE
Scope Family to an Organization

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#334]
As we plan the multi-tenancy of the application, a Family should belong to an Organization.

Acceptance Criteria:

- [x] Add a belongs_to relationship on Family
- [x] Add a has_many relationship on Organization
- [x] Add an organization_id column to Family with an index
- [x] Update existing factory for Family with an organization
- [x] Add specs to Organization and to Family for the added relationship

**Comment by haydenrou** [comment]
In the family CRUD, we have used `Family.all` to show families on the index page - we'll want to make use of a scope here per organisation, instead of showing all when this task is being done.
