### ISSUE TITLE
Remove unused JSON endpoints.

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/abalone#353]
As much of the application in its current state was built with  Rails scaffolds, we have a good number of controllers that _can_ respond with JSON that do not need to. Lets clear out these unused code paths so there isnt any confusion down the road.

**Comment by LittleBigProgramming** [comment]
I have raised a PR to remove unused endpoints found by traceroute. If you please assign this to me and if there is any further changes please let me know! 🙂🙏
