### ISSUE TITLE
Add SHL_number to Animal

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#387]
Animals from each spawning date and from each wild collection have a unique case number created by California's state Shellfish Health Laboratory (SHL).  Sometimes animals from a single spawning date have more than one SHL number.

I think there are a couple pieces to discuss here. The SHL_number terminology is probably unique to shellfish. Should we use a more generic column name here? Since animals can have more than 1 shl_number, we may want to consider having this be an array column.

**Comment by haydenrou** [comment]
Add SHL to CSV import too

**Comment by haydenrou** [comment]
Having discussed this, we are going to go down the route of adding a serialized array column to the animal and allowing the user to input one or many shl numbers in a comma separated list. They will also be able to add these in a csv import.

The idea being that they could update these in bulk through csv import in the future.
