### ISSUE TITLE
Tags: Rework how Animals are identified within an organization

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/abalone#397]
Currently Animals have a few different attributes that are used as identifiers. We have both `tag_id` and `pii_tag`, neither of which _really_ meets our needs. After talking with our stakeholders, we have learned that a `tag` on an animal is _really_ a combination of the color of a tag and a three digit number on that tag. So an individual animal might be identified by "Green 127" or "Yellow 341". These tags are usually written in lab notes or recorded in excel files as shorthand, `G127` or `Y341` from the examples here.

Tags are also, not always unique to animal, but they ARE always unique to an animal within a Cohort. There may be two animals identified as `G127`, but never two animals that belong to the same cohort. As such, we _believe_ that an animal can be uniquely identified by a combination of their tag and the cohort they belong to.

**Comment by CraigJZ** [comment]
I am thinking that the introduction of a string field that would get combined with 1 of the integer fields to form `Green_185`, for example, might be a simple way to go.

**Comment by haydenrou** [comment]
> I am thinking that the introduction of a string field that would get combined with 1 of the integer fields to form Green_185, for example, might be a simple way to go.

Do you mean we should keep but repurpose both tag_id and pii? Or are we expecting to drop these two and create two new columns, or one new column?

**Comment by benreyn** [comment]
I think... 
1. Drop tag_id, as we never really know what that was for
2. Rename pii_tag to `tag_number`
3. Add the new column for `tag_color` (or whatever other path seems right for this, if thats a `tag_color` table with a relationship, then I think thats fine too.

The important things to keep in mind here are...
1. A tag, like `G127` is not unique to animal, but unique to an animal within a cohort (cohorts now have_many animals as of #408 
2. When data gets imported into the application, the way that it usually will come in is in a CSV with a tag shorthand for an individual animal. Picture...

```csv
animal,length
G125,55
G126,43.2
G127,38
```
etc etc.

We want to make sure these operations can be done relatively performantly and without too much of a hack in the import code, but it IS _probably_ worth separating the concept of a tag color and the number for that tag? This _might_ be something we regret in the future, so happy to hear about an alternative if you have a good idea for one.
