### ISSUE TITLE
Diagnose style differences between development and production environments

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#426]
Review environment configs and assets and determine the cause of the styles not showing as expected in production.

https://abalone-staging.herokuapp.com/

Local:
<img width="1297" alt="Screen Shot 2020-09-29 at 10 01 32 PM" src="https://user-images.githubusercontent.com/7053190/94635742-5db40080-02a1-11eb-9b7a-86f22717e937.png">

Production:
<img width="1043" alt="Screen Shot 2020-09-29 at 10 01 19 PM" src="https://user-images.githubusercontent.com/7053190/94635797-79b7a200-02a1-11eb-8bca-350d7e49e5c0.png">

**Comment by benreyn** [comment]
I did some digging @CraigJZ. For one, it looks like we're pulling bulmaCSS through a CDN link in the layout. We also are still importing bootstrap. I think it might be good to clear out everything but tailwind, and then start addressing places where the design breaks down (and maybe do these two things together so we dont have a visually broken app at any point)

**Comment by rebeccapinheiro** [comment]
Hi, can I work on this one?

**Comment by benreyn** [comment]
@rebeccapinheiro, Please! Feel free to take a look at it. There may actually be a couple of separate tasks here. There are currently three separate CSS frameworks being pulled into the app in different ways. BulmaCSS is being added via a CDN in the `head` tag of `layout.html.erb`. The last time I looked at removing it, it broke alot of the styles in nav bar. We are also pulling in Bootstrap and a handful of handwritten styles via the asset pipeline. Finally we are pulling in TailwindCSS via webpack. Ultimately the only thing we want to be using is Taildwind.

If there are multiple tasks that this can be broken out into feel free to comment here or open additional issues. We would ideally like to keep Pull Requests for this small, but that may not necessarily be possible.

**Comment by rebeccapinheiro** [comment]
Hi @benreyn, I've been re-writing the nav bar, but I've also found some other places that depends on Bulma. I've done some tweaks to fix that while I remove Bulma completely. Can we break this task in 3? I will submit the first PR with the missing part of Tailwind, we create another issue for removing Bulma and I've also notice that the navbar is not 100% responsive and I have a fix for that as well. is that ok?

**Comment by CraigJZ** [comment]
@rebeccapinheiro Apologies for the delayed reply. Thanks for taking a look at this!! Yes, I think splitting this into the issues you proposed sounds good. I've added those issues and assigned you to them.
