### ISSUE TITLE
Address devise bypass deprecation in `/app/controllers/passwords_controller`

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#427]
Update the use of Devise's bypass option in `PasswordsController#update` to address deprecation warning.

Additional information: https://github.com/heartcombo/devise/pull/4078/files

Acceptance Criteria:

- [ ] Deprecation warning has been cleared
- [ ] Existing specs are passing

**Comment by cdarne** [comment]
Hi! I'd like to help with that issue. I've just created a PR to fix it.
