### ISSUE TITLE
Feature specs for updating an Animal

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#432]
Add features specs for  updating an animal record. 

Acceptance Criteria:

- [ ] Specs cover the expected behavior when updating an animal through the UI
- [ ] Specs are passing

**Comment by fiteclub** [comment]
Hey, I'm a newcomer and interested in working on this.  Mind if I take a look at this?

**Comment by CraigJZ** [comment]
@fiteclub Please do. And please feel free to reach out if you have any questions. Thanks!!
