### ISSUE TITLE
Introduce concept of mortality

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#433]
The proposed addition of a mortality concept would add a new mortality_events table. Mortality Events have a relationship to both animals and cohorts. An animal `has_one` mortality event. A cohort `has_many` mortality_events.

Examples:
Animal - A single, specifically tracked animal dies

```
mortality_date: 10/6/20
animal_id: 1234
cohort_id: animal.cohort.id
mortality_count: 1
```

Cohort - Animals belonging to a cohort are found dead

```
mortality_date: 10/6/20
animal_id: null
cohort_id: cohort.id 
mortality_count: 23
```

- [x] Add a mortality_events table with the following fields:
  - mortality date (datetime)
  - animal_id (bigint)
  - cohort_id (bigint)
  - mortality_count (bigint)
- [x] Add a method on Animal to determine if it is alive based on the absence of a mortality_event.
- [x] Add a method to cohort that returns the total mortalities for that cohort
- [x] Add specs to verify the relationships on both models 
- [x] Add spec for the new mortality method on Animal 
- [x] Add spec for the new mortality method on Cohort
- [x] Update seeds file

This ticket may be broken out into smaller ones or revised based on continuing discussions.

**Comment by CraigJZ** [comment]
@benreyn From my reading of the sample data, it looks like mortality could be expressed through a measurement with the date and number of mortalities being the key data points. Does this interpretation sound right or should it live as a more concrete concept in the app?

**Comment by benreyn** [comment]
I think we will also need a way to track a specific animal as being deceased. I worry that a measurement and a count would lead to us count animals as alive that we know to be dead.

**Comment by CraigJZ** [comment]
Ok, that makes sense. Thanks! I'll think a bit more about this and try to get something spec'd out for us to take a look at.

**Comment by CraigJZ** [comment]
@benreyn I sketched out what I think might work here in the description. When you have a chance, I'd love to get your thoughts.

**Comment by haydenrou** [comment]
Hi @CraigJZ @benreyn I'd be happy to pick this up. Are there any further details before I give it a go?

**Comment by CraigJZ** [comment]
Hi @haydenrou  Thanks! The details in the issue are how I'm seeing this conceptually but if you have any questions or suggestions along the way, I'm happy to chat through them.
