### ISSUE TITLE
Update statistics on home page

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#434]
The application home page currently shows a set of static statistics. We would like to change these so they pull 3 statistics from the current organization. To start, we can show the number of facilities, the number of cohorts and the number of animals. For now, let's use the same 3 statistics for all organizations, however, in the future we may want to have these differ per organization based on what is most meaningful for individual organizations.

Acceptance criteria:

- [ ] Add logic to only display the statistics when logged in.
- [ ] Add dynamically populated data for facilities, cohorts and animals based on the `current_organization`
- [ ] Add feature specs for this display

**Comment by PuZZleDucK** [comment]
From the 'jargon' part of the readme it looks like "No. of Spawn Dates" would be the number of "cohorts" in an organization... is that right?
