### ISSUE TITLE
Add model level validations to Cohort

### ISSUE THREAD

**Issue by benreyn** [rubyforgood/abalone#437]
Add model level validations to Cohort

- [ ] name: presence and uniqueness (scoped to organization)
- [ ] Enclosure: presence

**Comment by nsiregar** [comment]
Hi, I was trying to understanding what is the relation between `Cohort`, `Enclosure`, and `Operation` it seems like `Operation` was used to update the `Cohort` to `Enclosure`. If we would like to validate the presence of `Enclosure` in `Cohort`, shouldn't it be sufficient with the `required: true` in `belongs_to: :enclosure` association?

**Comment by CraigJZ** [comment]
Hi @nsiregar. I'm so sorry we missed your previous message. Yes, an Operation removes a Cohort from or adds a Cohort to an Enclosure.  For the presence validation of Enclosure on Cohort, yes, the `required: true` adds that validation. As of Rails 5, I believe `required: true` is the default for a `belongs_to` and doesn't have to be written out.
@benreyn Is there anything I'm missing here?

**Comment by kaysiz** [comment]
@benreyn has this been done already, if not can I do it?

**Comment by LawrenceWhalen** [comment]
@CraigJZ I asked Rebecca she let me know I could take over here it that would be alright with you.

**Comment by CraigJZ** [comment]
@LawrenceWhalen Yes, that's alright with me.

**Comment by LawrenceWhalen** [comment]
@CraigJZ Requiring a cohort to have an enclosure breaks the functionality of operations. Do we want operations to delete a cohort that no longer has an enclosure, or assign the cohort a standby enclosure until it is needed again?

**Comment by LawrenceWhalen** [comment]
Another option would be to have it only validate on creation or some other limited validation.
