### ISSUE TITLE
Refactor: We think that SHL number should really belong to cohort, and not Animal?

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#459]
- [ ] Create a cohort_shl_numbers table with the following fields:
  cohort_id (bigint) (index)
  shl_number_id (bigint) (index)
- [ ] Add CohortShlNumber model
- [ ] Add belogs_to relationships to Cohort and Shl_number to CohortShlNumber
- [ ] Add has_many cohort_shl_numbers relationship to Cohort 
- [ ] Add has_many shl_numbers through cohort_shl_numbers relation to Cohort 
- [ ] Add specs to test new relationships
- [ ] Remove animals_shl_numbers table 
- [ ] Remove animals_shl_numbers relationship on Animal
- [ ] Remove relevant specs 

For discussion: Should an animal inherit an Shl_number from its cohort? I think so.

This issue may be spit up into smaller tasks pending discussion.

**Comment by mattwd7** [comment]
I'm keen to take this on as soon as it has the green light!
