### ISSUE TITLE
Display the name of the current organization when a user is logged in

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#470]
We would like to display the name of the current organization when a user is logged in. Between the navigation and main content may be an attractive place for this.

Acceptance Criteria:

- [ ] Add logic for dynamically displaying the current_organization name when a user is logged in
- [ ] Style the display so it fits nicely within the current styling (for context - we are using to TailwindCSS)
- [ ] Add specs to test that the correct organization name is displayed
- [ ] Add specs to test the the name is only displayed when a user is logged in

**Comment by gabrielbaldao** [comment]
Can I do this?

**Comment by metamoni** [comment]
Hi there 👋

I'd like to work on this one

**Comment by CraigJZ** [comment]
Great! Thanks @metamoni
