### ISSUE TITLE
Remove Unused Bootstrap code

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#472]
The application is moving away from Bootstrap to TailwindCSS. The bootstrap gem is still being used and Bootstrap is still being imported. We would like to. remove this and any other remaining references. 

Acceptance Criteria:

- [ ] Remove bootstrap gem
- [ ] Remove bootstrap references and related-code from assets
- [ ] Review application visually and note any broken styles (we will split these, if any, into separate issues)

**Comment by chelsieng** [comment]
I am working on it :)

**Comment by LittleBigProgramming** [comment]
Hey, can I pickup this issue please? 🙂

**Comment by CraigJZ** [comment]
Yep! Thanks!!

**Comment by LittleBigProgramming** [comment]
Hi, 

I have raised a PR for this, though the only issue I could see visually as per _Review application visually and note any broken styles (we will split these, if any, into separate issues)_ was in the notices/alerts. These could be updated to use one of the styles from https://tailwindcss.com/components/alerts 🙂

**Comment by CraigJZ** [comment]
Thanks @LittleBigProgramming! I am not finding anything major either. :) 

That looks like a good solution for the notices/alerts. I'll try to get issues up for that and a few other minor fixes soon.
