### ISSUE TITLE
Facilities: Edit and Trash icons do not have accessible titles or labels

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#536]
Every edit (pencil) and trash (trashcan) icon needs an accessible title. This can either be putting text into the link, or it can be adding an aria-label or something similar.

![edit-trash-links-need-titles](https://user-images.githubusercontent.com/45127691/102561297-56331500-40a2-11eb-8345-8ce42e092eb0.PNG)

**Comment by metamoni** [comment]
Hello 👋

I pushed up a PR for this.
