### ISSUE TITLE
Animals: Table needs scope and a heading

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#546]
Table headings need a scope defined (`scope="col"`) and the actions column needs a column heading

![animals-table-needs-scope](https://user-images.githubusercontent.com/45127691/102562802-d9099f00-40a5-11eb-8961-08067f9f3369.PNG)

**Comment by pschlatt** [comment]
@CraigJZ If you want to go ahead and assign me this one, I believe I'm almost done and I'll submit a PR your way soon.
