### ISSUE TITLE
Uploads:Uploaded Files: links need unique names

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#555]
This might not be an issue, but each of the filenames needs to have a unique name or title for the link. Currently it says "bad.csv". The link targets are unique. 

![uploaded-files-unique-names](https://user-images.githubusercontent.com/45127691/102563612-ad87b400-40a7-11eb-9f3b-e3ceb1597a56.PNG)

**Comment by metamoni** [comment]
I can look into this 👍

**Comment by Nalisa8** [comment]
I would like to work on this one

**Comment by Nalisa8** [comment]
Wanted to fix the issue, but unfortunately since the uploader is not working, doesn't simplify the debugging and the testing of it. The problem might be coming from the upload action in the file_uploads_controller. it is not passing the unique name to uploaded files.
