### ISSUE TITLE
Uploads: File Uploads: font contrast on "Remove" buttons

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#556]
The "Remove" buttons need better font contrast. Making the text white might be enough.

![file-uploads-text-contrast](https://user-images.githubusercontent.com/45127691/102563708-e32c9d00-40a7-11eb-8dde-3b65893ce3b6.PNG)

**Comment by metamoni** [comment]
Hi,

I tried to reproduce this, but couldn't. Looks like the colours have already been changed.

<img width="1437" alt="Screenshot 2021-02-26 at 11 47 58" src="https://user-images.githubusercontent.com/22390758/109296804-d86d5180-7828-11eb-9f37-e1f1cd822109.png">

**Comment by metamoni** [comment]
I'll take this one :)
