### ISSUE TITLE
Admin:Users font-contrast in table headings

### ISSUE THREAD

**Issue by NiquiCara** [rubyforgood/abalone#565]
The table headings don't have enough font contrast. Need moar contrast.

![users-font-contrast](https://user-images.githubusercontent.com/45127691/102564401-5e428300-40a9-11eb-98e9-f9ac46096431.PNG)

**Comment by noahc** [comment]
How can I reproduce the report you have above?

**Comment by CraigJZ** [comment]
@noahc, @NiquiCara might be able to provide more insight but I believe the tool being used here is [ANDI](https://github.com/SSAgov/ANDI).

**Comment by NiquiCara** [comment]
Apologies! Going to tag in @armahillo here, who helped with issue creation.

**Comment by noahc** [comment]
Thanks! I was able to use the link provided to get ANDI installed.
