### ISSUE TITLE
Backend - Calculation for Histogram

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#58]
The histogram is at `/reports` under the Growth tab.

We need to adjust the calculation we are using for the histogram on the backend. There are some calculations in `app/lib/aggregates.rb`, but we need to make sure they match the below requirements:

For histograms, bins to be by 1 cm increments, so 0-0.99 cm, 1-1.99 cm, etc. Our largest animal is just over 18 cm and the max listed size for a white abalone is 10 inches (25.4 cm), so it's probably safe to say we wouldn't ever have one over 30 cm. For a specific bar in the histogram, here is a scenario: Say I want to know X, the number of animals in the 4-4.99 cm bin, for the SF15-77 cohort animals:

N = the number of animals that were 4-4.99 cm in length in the most recent uploaded spreadsheet (Untagged AND Tagged animals) with length data for that cohort
S = the total number of animals measured in the same spreadsheet, i.e., the most recent uploaded spreadsheet with length data for that cohort (Untagged AND Tagged animals)
T = the total number of estimated animals in the cohort = the total number counted on the most recent count closest to the length measurement date minus the mortalities since then

X = (N/S)*T ... or the proportion of animals that were measured that were in that size bin, scaled up to the total predicted number of animals in that cohort.

The histogram calculations should have the following parameters (you should be able to pass in one or both):
1. cohort, or multiple cohorts
2. Optional date range

**Comment by wesleyeewong** [comment]
I'd like to take this on, but I still have some questions.

Would I create a new endpoint for this, or replacing the current logic for `lenghts_for_measurement` in `ReportsController`?

What should the json response look like?

**Comment by corneliusellen** [comment]
Hey @wesleyeewong, I've actually grabbed this one to work on and am just waiting for some input from the stakeholder before I push a PR up. It would be super helpful to have your review on it though.

**Comment by wesleyeewong** [comment]
@corneliusellen ah my bad, didn't see that you took it. And will be happy to help out with the review.

**Comment by jtu0** [comment]
Hey @corneliusellen do you still have a branch with your work you can share?

**Comment by mdworken** [comment]
Blocking this for now - will reopen a similar one once we get the list of priority data reports from pinto!
