### ISSUE TITLE
Backend/Frontend - Bulk Upload for Import Data

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#60]
Users should be able to select multiple CSV files of the same type to be uploaded/parsed on this page: http://abalone.blrice.net/file_uploads/new.

_Acceptance Criteria:_
As a user, I can upload a maximum of 10 CSV files in bulk of the same type (e.g. Untagged Animal Assessment) from my computer.

**Comment by colinsoleim** [comment]
I'll try and tackle this issue next!
