### ISSUE TITLE
Multiple <h1>s on homepage 

### ISSUE THREAD

**Issue by metamoni** [rubyforgood/abalone#621]
Pages should only have one main heading (unless we decide to use multiple `<h1>s` (see #532), representing the most important idea on the page. At the moment, this is 'Abalone Analytics'.

The rest of it needs a bit of restructuring. Following [these requirements](https://www.w3.org/WAI/tutorials/page-structure/headings/) and [this example](https://www.w3.org/WAI/tutorials/page-structure/example/), we could logically structure the page like so:

```
<h2>Your Organization: White Abalone</h2>
<ul>
  <li>Animal count: 132</li>
  <li>facility count: 12</li>
  <li>cohort count: 12</li>
</ul>
```

We have a lot of `div`s on the page at the moment, all from bootstrap, so maybe jamming a list in between those isn't the best. But we can follow the same pattern and use `div`s instead of my proposed `ul` and `li` tags. As long as we keep the same styles we'll get the same result visually. But when on a screen reader, this will read out 'Abalone Analytics' as the main heading, your organization's name as `<h2>`, and then the animal/facility/cohort counts under that.

**Comment by metamoni** [comment]
I'm happy to work on this one, by the way. I'll push up a PR for it :)

**Comment by CraigJZ** [comment]
Thank you for adding this issue! I like your proposed structure and am okay with using a list there.

I added my thoughts on #532 but let me know if you have any concerns with that approach. Overall, my preference for this app would be using a single `<h1>` per page.
