### ISSUE TITLE
Testing - Write Feature/Integration Tests for TaggedAnimalAssessmentJob

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#64]
Tests need to be written for `TaggedAnimalAssessmentJob`.

Please use this fixture file for testing: `db/sample_data_files/tagged_animal_assessment/Tagged_assessment_12172018 (original).csv`

**Feature/Integration Tests**
The following contexts and expected outcomes should be tested:
1. Context: The user uploads a CSV that has already been processed.
Outcome: 
- A new `ProcessedFile` record should be created 
- On the /file_uploads page, the user should see:
  - File has Status: "Failed"
  - File has Errors: "Already processed a file with the same name. Data not imported!"
  - File has Statistics: "{}"

2. Context: The user uploads a CSV with invalid headers.
Outcome:
- A new `ProcessedFile` record should be created 
- On the /file_uploads page, the user should see:
  - File has Status: "Failed"
  - File has Errors: "Does not have valid headers. Data not imported!"
  - File has Statistics: "{}"

3. Context: The user successfully uploads a CSV with no errors:
Outcome:
- A new `ProcessedFile` record should be created 
- 201 new `TaggedAnimalAssessment` records should be created
- On the /file_uploads page, the user should see:
  - File has Status: "Processed"
  - File has no Errors
  - File has Statistics: "{row_count: 201, rows_imported: 201, rows_not_imported: 0, shl_case_numbers: {"SF16-9A": 100, "SF16-9B": 21, "SF16-9C": 11, "SF16-9D": 69}}"

4. Context: The user successfully uploads a CSV with errors for 2 rows:
Outcome:
- A new `ProcessedFile` record should be created 
- 199 new `TaggedAnimalAssessment` records should be created
- On the /file_uploads page, the user should see:
  - File has Status: "Processed"
  - File has Errors: "Does not have valid headers. Data not imported!"
  - File has Statistics: "{row_count: 201, rows_imported: 199, rows_not_imported: 2, shl_case_numbers: {"SF16-9A": 100, "SF16-9B": 21, "SF16-9C": 11, "SF16-9D": 69}}"

**Comment by rafaltrojanowski** [comment]
Hi @corneliusellen! I'm on it.

**Comment by rafaltrojanowski** [comment]
@corneliusellen 

I've already implemented 1), 2) and 3). The question is, which file can I use for:
4) - CSV with errors for 2 rows

Also, is there a file with invalid headers in the repo already (2))? I've prepared a file, but maybe that is not necessary. Thanks!

**Comment by rafaltrojanowski** [comment]
@corneliusellen Thanks for your review, added a few commits, I believe it's ready now :)

**Comment by corneliusellen** [comment]
Just merged!
![bitmoji](https://render.bitstrips.com/v2/cpanel/cb80dd8b-4a88-476a-a82b-1e1e71ade13b-9476026c-06cf-40d5-9670-8a85c9bb620e-v1.png?transparent=1&palette=1&width=246)

**Comment by rafaltrojanowski** [comment]
@corneliusellen Thank you so much!
