### ISSUE TITLE
Testing - Write Unit Tests for ImportJob

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#65]
Tests need to be written for `ImportJob`, which is a module used by all the CSV import jobs.

**Unit Tests**
The following methods should be unit tested:
- #initialize_processed_file
- #validate_headers
- #import_records

**Comment by rafaltrojanowski** [comment]
Hi @corneliusellen 👋 I will have a look, I'm new to the project, and would like to contribute.

**Comment by rafaltrojanowski** [comment]
@marc Are you ok? Maybe that's something on your plate?

**Comment by wesleyeewong** [comment]
The PR is ready for review :)
