### ISSUE TITLE
Table content does not adjust to fit in Chrome/Safari

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#681]
It appears this bug is exclusive to Chromium and Webkit browsers. It has been observed in Chrome and Safari, so far. In those browsers tables with longer row content lose the content in the right-most columns. Currently this can be seen in Cohorts and Enclosures, but will like effect all tables with long content.

#540 and #548 depend on this issue.

Cohorts table in Firefox:
<img width="1284" alt="Screen Shot 2021-05-15 at 9 05 18 AM" src="https://user-images.githubusercontent.com/7053190/118362420-7ab1f100-b55d-11eb-98bc-d8aeac973c15.png">

Cohorts table in Chrome:
<img width="1281" alt="Screen Shot 2021-05-15 at 9 04 48 AM" src="https://user-images.githubusercontent.com/7053190/118362531-da100100-b55d-11eb-8576-5e76b3a134b6.png">

Acceptance Criteria:
- [ ] Update table styles and/or structure so the full content shows across browsers

**Comment by librod89** [comment]
I will work on this one.
