### ISSUE TITLE
Review test coverage

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#682]
Test coverage is spotty in some areas. Review full application and identify areas where tests are needed and existing tests should be refactored. Add individual issues for migrating controller specs. Once #683 is completed, add individual issues for migrating existing feature specs to system specs.

**Comment by pschlatt** [comment]
@CraigJZ [SimpleCov](https://github.com/simplecov-ruby/simplecov) would make this much easier.

**Comment by CraigJZ** [comment]
@pschlatt Agreed. Adding simplecov would be a good place to start on this one.
