### ISSUE TITLE
System Spec Setup

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#683]
We would like to begin the process of migrating the application to use rails system specs rather than feature specs. This issue will handle the initial setup and migrate over at least one set of feature specs to run as system specs. Ideally, we will run the feature and system specs side by side while we are migrating them all over.

Acceptance Criteria:

- [ ] Implement a basic setup for running Rails system specs. We want to keep things as close to the standard setup as possible using a headless browser
- [ ] Pick an existing set of feature specs to migrate over
- [ ] Update existing feature spec setup, if necessary, to allow them to run side-by-side during the migration
- [ ] Ensure that the test suite runs successfully

**Comment by rebeccapinheiro** [comment]
I think I need to work on this first right? can I pick this one up?

**Comment by CraigJZ** [comment]
Closed by #859
