### ISSUE TITLE
Backend/Frontend - Create Multiple Select List and Date Picker for Histogram Parameters

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#69]
There should be an area where the user can select parameters in the upper right hand side of the histogram chart at `/reports` under the Growth tab. The user should have the ability to select a measuring event (i.e. a certain population on a certain date) or a group of measuring events (different populations near the same date).

_Acceptance Criteria:_

- [ ] Backend - returns a list of cohorts 
- [ ] Frontend - Multiple select list of cohorts
- [ ] Frontend - Date picker

We use [Highcharts](https://www.highcharts.com/), a JavaScript library for rendering all graphs and charts.

**Comment by colinsoleim** [comment]
I'll work on this issue next!
