### ISSUE TITLE
Fix Warning on Cohorts Show action feature spec

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#708]
The spec at `spec/features/cohorts/show_spec.rb:19` throws the following warning:

`Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead.`

Refactor the spec to clear this warning.

**Comment by FionaDL** [comment]
Hello, I will work on this, hope that's ok!

**Comment by CraigJZ** [comment]
Sounds good! Thank you.
