### ISSUE TITLE
Successful file upload screen is not displaying all the imported data for a measurement

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#711]
The file upload show screen for a successfully processed file is missing the following data:

`measurement_type`
`measurement_event`
`enclosure_name`
`cohort_name`
`tag`

This missing data is being successfully added to the database. 

Current Display:

<img width="1237" alt="Screen Shot 2021-06-29 at 6 19 56 PM" src="https://user-images.githubusercontent.com/7053190/123874855-c569ab80-d906-11eb-99af-8ce5093111f8.png">

Acceptance Criteria

- [ ] Update table to display all successfully imported values
- [ ] Add specs to confirm this functionality

**Comment by librod89** [comment]
@CraigJZ I can work on this ticket
