### ISSUE TITLE
Brakeman

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#716]
We would like to install the [brakeman gem](https://github.com/presidentbeef/brakeman) to help with security.

- [ ] Install and configure brakeman gem
- [ ] Run initial scan
- [ ] Correct or file issues for any warning found in the scan

**Comment by sinn22** [comment]
@CraigJZ 
Hi,  I'm going to work on #716 and https://github.com/rubyforgood/abalone/issues/717 issues.

So I have one question.
Brakeman can detect 3 warnings(high, medium, weak). Do you want to detect all these warnings? Or do you want to detect only high ones?

**Comment by CraigJZ** [comment]
Hi @sinn22 Thank you for working on these. For this one, we would like to detect all 3 levels.

**Comment by sinn22** [comment]
@CraigJZ 
I create PR for this issue.
It is WIP, but I want to see if brakeman works well on CI.
Would you please approve to running CI in this PR ?
