### ISSUE TITLE
Migrate Feature Specs to System Specs

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#718]
Depends on #683 

Migrate Existing Feature specs to System specs. This is also an opportunity to audit the existing feature specs as we move them over.

- [ ] animals
- [ ] cohorts
- [ ] enclosures
- [ ] facilities
- [ ] file_upload
- [ ] locations
- [ ] measurement_types
- [ ] passwords
- [ ] users
- [ ] csv_upload_confirmation_spec.rb
- [ ] csv_upload_pagination_spec.rb
- [ ] delete_failed_file_upload_spec.rb
- [ ] download_csv_file_upload_spec.rb
- [ ] group_operations_in_operation_batches_spec.rb
- [ ] home_page_statistics_spec.rb
- [ ] new_measurement_spec.rb
- [ ] reporting_spec.rb
- [ ] upload_measurements_with_spaces_spec.rb

References:

- [https://edgeguides.rubyonrails.org/testing.html#system-testing](https://edgeguides.rubyonrails.org/testing.html#system-testing
)
- [https://relishapp.com/rspec/rspec-rails/docs/system-specs/system-spec](https://relishapp.com/rspec/rspec-rails/docs/system-specs/system-spec)
- [https://everydayrails.com/2018/01/08/rspec-3.7-system-tests.html](https://everydayrails.com/2018/01/08/rspec-3.7-system-tests.html)

**Comment by rebeccapinheiro** [comment]
Can I work on this one as well?

**Comment by CraigJZ** [comment]
Absolutely. Thank you @rebeccapinheiro
