### ISSUE TITLE
Only display saved queries in blazer for the current organization 

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#724]
The blazer interface displays links to all saved queries for all organizations. Queries for organizations other than the one a user is signed in for can not be accessed and throw an error when clicked. We should only display saved queries for the current organization. One potential path would be to set row level security on the blazer tables likely scoped to the creator's organization.

**Comment by mattwd7** [comment]
I'll give this a shot!

**Comment by mattwd7** [comment]
@CraigJZ can you assign me to this issue and/or add me as an abalone collaborator?
