### ISSUE TITLE
Handle measurement import with empty lines at the end of the file

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#725]
Attempting to perform a measurement upload using a csv file with empty lines at the end results in a failure. We would like to handle these case and successfully process the csv.

- [ ] Update upload processing to handle this use case
- [ ] Add relevant specs to test this case

**Comment by librod89** [comment]
@CraigJZ can I work on this ticket?

**Comment by CraigJZ** [comment]
@librod89 Yes, that would be great!
