### ISSUE TITLE
Ruby 3+

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#754]
Upgrade Ruby to the latest available release of Ruby 3.

[https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/](https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/)  
[https://github.com/ruby/ruby/blob/v3_0_2/NEWS.md](https://github.com/ruby/ruby/blob/v3_0_2/NEWS.md)  
[https://www.bigbinary.com/blog/ruby-3-features](https://www.bigbinary.com/blog/ruby-3-features)

- [ ] Upgrade the Ruby version to the latest release of Ruby 3
- [ ] Review and update code to fix any resulting issues and deprecations
- [ ] Update Docker configuration to use the new Ruby version
- [ ] Update the documentation to reflect the new ruby version
- [ ] Ensure specs pass and application runs locally

**Comment by librod89** [comment]
@CraigJZ can I work on this ticket?

**Comment by CraigJZ** [comment]
@librod89 Yes, that would be great. Thank you!
