### ISSUE TITLE
Navigation Review

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#786]
The standards rails indexes are not necessarily the views that will be most useful to the stakeholder. We would like to do an initial review of the navigation minimize the space used by the indexes to make room for links to views that the stakeholders will use more frequently.

- [ ] Move the `Facilities`, `Enclosures`, `Animals` and `Cohorts` into a single drop-down navigation. A proposed top-level name for this is `Statistics` but we are open to other suggestions.

We anticipate adding additional navigation items to Measurements in #845 and Key Reports in #795

**Comment by mattwd7** [comment]
Looks like this was covered as a part of #864 . PR here: https://github.com/rubyforgood/abalone/pull/864/files
