### ISSUE TITLE
DevOps: Set up CI/CD

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#79]
- [x] Look into postgres version... do we need to upgrade?
- [x] Decide and obtain new domain name
- [x] Set up continuous integration  to run tests automatically
- [x] Set up continuous deployment (3 applications are: database, background jobs and main application)

**Comment by anusha5695** [comment]
Hi @corneliusellen : Is this open for a PR?

**Comment by corneliusellen** [comment]
@anusha5695 hi! Thanks for your interest. This is actually being working on by the Optoro team, but feel free to pick up a different issue with a 'help wanted' or 'hackoberfest' label.

**Comment by anusha5695** [comment]
@corneliusellen : Sure thanks
