### ISSUE TITLE
Report: Live animal count by facility

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#790]
This report should be created in the staging app, under the White Abalone organization. The existing query that returns ALL animals by cohort can be used as a guide. 

`SELECT name, COUNT(*) FROM cohorts INNER JOIN animals on animals.cohort_id = cohorts.id GROUP BY cohorts.id`

- [ ] Create a query to track live animal counts by facility and display as a bar graph 
- [ ] Update seed data so the relevant data will be available to this query
- [ ] Comment on this issue with a screen shot of the completed report

Depends on #715 (making mortality available to Blazer queries)

**Comment by web-kat** [comment]
Hey @CraigJZ, Darren has been out the past two days. [I added the report to the staging environment here](https://abalone-staging.herokuapp.com/blazer/queries/5-animal-count-by-facility). 

Here is a screenshot of the report. I don't believe we will need to update the seed data for this report, but let me know if you would like to see any changes!

<img width="1183" alt="animal-count-by-facility" src="https://user-images.githubusercontent.com/38359249/137209546-6e7d0aac-0cea-4298-8c2c-b1b8d3cad618.png">

**Comment by CraigJZ** [comment]
Thanks @web-kat!! I think the only change we will need for this one is to scope it to only include live animals. #791 has a similar scoping on cohorts that may be a useful reference for this.

**Comment by CraigJZ** [comment]
@web-kat This looks great!! Thank you!!
