### ISSUE TITLE
Report: Live animal count by cohort

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#791]
This report should be created in the staging app, under the White Abalone organization. The existing query that returns ALL animals by cohort can be used as a guide. 

`SELECT name, COUNT(*) FROM cohorts INNER JOIN animals on animals.cohort_id = cohorts.id GROUP BY cohorts.id`

- [ ] Create a query to track live animal counts by cohort and display as a bar graph 
- [ ] Update seed data so the relevant data will be available to this query
- [ ] Comment on this issue with a screen shot of the completed report

Depends on #715 (making mortality available to Blazer queries)

**Comment by josephinef9** [comment]
claiming :)

**Comment by CraigJZ** [comment]
Thanks @josephinef9!!

**Comment by CraigJZ** [comment]
Added this query to the staging app. 🎉
