### ISSUE TITLE
Migrate controller specs to request specs

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#794]
We have a few controller specs and would like to migrate these to request style specs.

See here for some more discussion: [rspec/rspec-rails#1838](rspec/rspec-rails#1838)

References:

[https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec](https://relishapp.com/rspec/rspec-rails/docs/request-specs/request-spec)
[https://everydayrails.com/2016/08/29/replace-rspec-controller-tests.html](https://everydayrails.com/2016/08/29/replace-rspec-controller-tests.html)

- [ ] spec/controllers/file_uploads_controller_spec.rb
- [ ] spec/controllers/users_controller_spec.rb

This is also a good opportunity to review our existing coverage in this area and add new issues for any areas that lack adequate coverage.

**Comment by rebeccapinheiro** [comment]
Can I work on this?

**Comment by gabrielbaldao** [comment]
Can I help to create some new specs?
