### ISSUE TITLE
Collection attributes on Animal might confuse collection from the wild and naturally spawned animals

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#796]
Animal currently has the following attributes:

`collection_year`
`date_time_collected`
`collection_position`

These names make sense for animals that are collected from the wild but may cause confusion for animals that are spawned. These two processes of introducing animals are very different in practice and that needs to be reflected clearly in the data. For the stakeholders, "collected" refers to an animal being collected from the wild and "fertilized" (or spawned) refers to an animal that has been introduced naturally.

One proposed path here would be to create additional attributes that denote when an animal is spawned. The terminology proposed by the White Abalone group is 

`fertilized_year` or `spawned_year`
`date_time_fertilized` or `data_time_spawned`

Another possible solution would be rename the existing collection columns to something that could work for either collected or spawned animals. We would then add an attribute that denotes if an animals was collected or spawned. Perhaps something like `entry` with `spawned` or `collected` as options. 

Acceptance criteria
- [ ] Determine which option to move forward with
- [ ] Add the relevant attribute
- [ ] Update specs
- [ ] If the existing collection attributes are changed, update relevant usages in the system including views and seed data.

**Comment by metamoni** [comment]
Hi,

How about renaming the existing collection columns to something like: `entry_year`, `entered_at` (date), `entry_point` (or `entry_location`, `null` by default) for the generic columns names? Then we'd have `collected` as a boolean, and `entry_point` is required if `collected` is `true`.

**Comment by CraigJZ** [comment]
Hi @metamoni,
This sounds like a good solution for this issue. Thank you! 
I would probably lean toward `entry_point` over `entry_location`.
Would you like to take this one?

**Comment by metamoni** [comment]
Absolutely! ☺️
