### ISSUE TITLE
Backend/Frontend: Better CSV Upload Errors

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#80]
_Acceptance Criteria:_
As a user, when I upload a CSV and it fails to process, I go the the page `/file_uploads` and:
1. See the failed file with name, date, category, 'failed' status, stats and initial errors
2. Click on the failed file 
3. See detailed errors: which rows failed and why
4. Fix the errors on the original CSV on my machine
5. Click a button to re-upload my edited CSV.

**Comment by rafaltrojanowski** [comment]
Great idea, I was thinking about it when I was working on #67. Actually, the main struggle was not knowing which headers don't match. Is that something that we would need to have as well?

Regarding AC, I will have look what can be done.

**Comment by corneliusellen** [comment]
@rafaltrojanowski good point, we would want to show the user if headers were incorrect as well. I'll open a separate issue for that. Would you like to work on it?

**Comment by rafaltrojanowski** [comment]
@corneliusellen Yes, please.

**Comment by yportnoy** [comment]
@corneliusellen does this mean you do not want us to work on this?

**Comment by corneliusellen** [comment]
@yportnoy No, this issue is still assigned to the Optoro team, but I made a separate [Issue](https://github.com/rubyforgood/abalone/issues/84) for header errors. I think CSV upload errors can be broken down into header errors and row errors, and can be worked on concurrently. LMK if you disagree.

**Comment by rafaltrojanowski** [comment]
Just to clarify, I didn't know what exactly `optoro-hackathon-day` label means, sorry. 
I'm happy to hand over this task.

Considering that it requires to decide which tool to use for background job - frontend communication, I think I would be better to wait with #84. Let me know if I'm wrong.

On the positive side, I have solved a header validation problem partially here: 
https://github.com/rubyforgood/abalone/pull/83 so it's noting urgent from my side.

**Comment by jtu0** [comment]
@corneliusellen When there are CSV upload errors, should the app try to import what it can from the bad file, or should the app refuse to import any rows from a file with CSV upload errors?
