### ISSUE TITLE
Set up linter/style rules

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#81]
We want to have a basic linter set up and enforced for new PRs.

**Comment by yportnoy** [comment]
https://github.com/rubocop-hq/rubocop

**Comment by morhook** [comment]
Linking PR: https://github.com/rubyforgood/abalone/pull/90

**Comment by sarslanoglu** [comment]
@corneliusellen Is this issue still not completed? I can work on it if needed
