### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#841]
We have been asked to add a "landing" page for the application. Here [is an example](https://humanessentials.app/) from Ruby For Good's Human Essentials App. As abalone is a younger application, its landing page would not be focused on bringing on additional users but rather providing a visually appealing overview of what the application does, attracting new code contributors and providing entry navigation as the current home page does. If we could incorporate the existing abalone analytics graphic, that would be great too!

Here is some information and suggestions that may be helpful when deciding on design elements:

What the application does:
- Collect and import data on abalone
- Analyze data to determine trends, identify problems and track outcomes

Attracting new contributors:
- Possibly make existing menu items linking to about more prominent on the landing page

**Comment by vurtn** [comment]
i'm on it !

**Comment by rruiz85** [comment]
@CraigJZ I'm currently working on a PR for the landing page now. Let me know if you can approve and merge so that the rest of the team can pull the latest and merge my changes to their branch.
