### ISSUE TITLE
Fix color of buttons after measurement submission 

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#894]
We would like to update the 2 buttons on `upload.html.erb` to match the style of other buttons in the application

Current design:
<img width="446" alt="Screen Shot 2021-11-07 at 12 12 44 PM" src="https://user-images.githubusercontent.com/7053190/140846977-9c9e2361-6ca2-4468-888a-70c6f6c87271.png">

- [ ] Update the style and color for the 2 buttons on `views/file_uploads/upload.html.erb` to match other buttons in the application 
- [ ] Use tailwind styles 
- [ ] Update any relevant specs

**Comment by mattwd7** [comment]
After working with file uploads on a separate issue, I've put a quick one together for this. Sorry to swoop, @vurtn !
