### ISSUE TITLE
Update style and spacing for Generate Template button 

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#900]
The “Generate Template” button on /measurements/new overlaps the selection field. We would like to update the button style and spacing using Tailwind styles. 

<img width="596" alt="Screen Shot 2021-11-07 at 12 12 01 PM" src="https://user-images.githubusercontent.com/7053190/140850864-c402288d-c148-4a7c-b2a3-4b7fa3e8675b.png">

- [ ] Update button styles
- [ ] Update any corresponding specs

**Comment by vurtn** [comment]
i'm on it !
