### ISSUE TITLE
Prevent the deletion of Measurement Types that have already been used in measurements

### ISSUE THREAD

**Issue by CraigJZ** [rubyforgood/abalone#901]
We would like to prevent the deletion of measurement types that are already being used in measurements. The way we handle this for Exit Types can serve as an example for handling this issue. 

- [ ] Update the controller destroy action to prevent deletion of measurement types that have associated measurements and provide a helpful flash notice 
- [ ] Update the measurement types index to hide the delete icon for measurement types that have associated measurements
- [ ] Add specs to test both of these changes
- [ ] Update any existing relevant specs

**Comment by mattwd7** [comment]
Ooo, I want it! I'll get started first thing tomorrow 😄
