### ISSUE TITLE
Admin can create new users

### ISSUE THREAD

**Issue by jtu0** [rubyforgood/abalone#93]
_This issue builds on the devise work done in https://github.com/rubyforgood/abalone/pull/76/_

We need a way for new users to be created through the app.  This should be as lightweight and minimal as possible.  There is no guarantee we can send email reliably, otherwise [`devise-invitable`](https://rubygems.org/gems/devise_invitable/versions/2.0.1) would be a good choice.

- [ ] Add [`administrate`](https://github.com/thoughtbot/administrate) to Gemfile, `bundle`
- [ ] Create a User-admin dashboard: `rails generate administrate:dashboard`
  - You might need to create a `user` model
  - [`users` table was already created in PR 76](https://github.com/rubyforgood/abalone/pull/76/commits/39ea235ce2bf5441efb6c1283d0749ecfd8e7560)
  - [ ] If you need to create the `user` model, it should include `name` and `email`. Devise will probably want `password` and maybe some other stuff.
  - [ ] Make sure you can still login with the test user (from db/seed)

Confirm that you can do the following:
- [ ] Can login and logout with the test user from db/seed

As an authenticated user:
- [ ] Can create a new user and supply a name and email
- [ ] Can delete a user

Don't worry too much about roles - do whatever is simplest and least code.  If that means everyone is an admin, start there.

Please pop into the #abalone channel in rubyforgood.slack.com if you have any questions or want to grab this issue.

**Comment by benreyn** [comment]
@CraigJZ to break this into multiple user stories

**Comment by CraigJZ** [comment]
Separate issues added the tasks involved in completing this issue. Closing.
