### ISSUE TITLE
Add TaggedAnimalAssessment model validations

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#95]
_Acceptance Criteria:_
- [ ] As a user, I want to be able to upload a CSV of category found in `sample_date_files/tagged_animal_assessment` on the page `/file_uploads/new` with correct data formats. I should see errors if there are incorrect data formats.
- [ ] Model Validations
- [ ] Unit tests for model validations

Please refer to the [data dictionary](https://github.com/rubyforgood/abalone/wiki/Abalone-Data-Dictionary) and the notes below for coding the model validations. For an example, please look at: [Example of WildCollection model validations and spec](https://github.com/rubyforgood/abalone/pull/89/commits/9054bf20f821de658a2a028549d4a26ab632c3a9)

`TaggedAnimalAssessment.rb`
- Required: measurement_date, shl_case_number, spawning_date, tag, length
- See data dictionary for specific formats for shl_case_number, tag, predicted_sex and gonad_score
- length should be float not exceed 100
- measurement_date and spawning_date should be valid date with month, day, and year
- Columns E-J treated as a note/strings

**If there is a column  for Facility, let's make these foreign keys to the `Facility.rb` model we already have. There should only be certain facilities (see the `seeds.rb` file and users have the ability to add new ones.)

**Comment by edwinthinks** [comment]
I can take this one :)

**Comment by edwinthinks** [comment]
Opened https://github.com/rubyforgood/abalone/pull/123 to address this
