### ISSUE TITLE
Add MortalityTracking CSV upload job and model validations

### ISSUE THREAD

**Issue by corneliusellen** [rubyforgood/abalone#97]
_Acceptance Criteria:_
- [ ] As a user, I want to be able to upload a CSV of category found in `sample_date_files/mortality_tracking` on the page `/file_uploads/new`.
- [ ] Test should be written for this job similar to `spec/jobs/tagged_animal_assessment_job_spec.rb`
- [ ] Model Validations
- [ ] Unit tests for model validations

**Notes:**
Much of the logic for the file uploading/parsing is already written in the module concern `ImportJob`.

The heaviest lifting will be adding appropriate validations for the ```MortalityTracking``` model. Please refer to the [data dictionary](https://github.com/rubyforgood/abalone/wiki/Abalone-Data-Dictionary) and the notes below for coding these. For an example, please look at: [Example of WildCollection model validations and spec](https://github.com/rubyforgood/abalone/pull/89/commits/9054bf20f821de658a2a028549d4a26ab632c3a9)

**If there is a column  for Facility, let's make these foreign keys to the `Facility.rb` model we already have. There should only be certain facilities (see the `seeds.rb` file and users have the ability to add new ones.) 

`MortalityTracking.rb`
- Required: mortality_date, cohort, shl_case_number, spawning_date, # of morts (some might be unknown see note from lab)
- See data dictionary for specific formats for cohort, shl_case_number, tag
- motality_date and spawning_date should be valid date with month, day, and year
- Note from lab:
_These are the data that are probably going to need the most attention and QA/QC on
our end. One challenge here is that mortalities are currently being tracked on this
datasheet via a single entry for each population/location collected from at a single time
point. When there are multiple tagged animals collected at a single timepoint, all the
tagged animals are all lumped together in a single entry on this data sheet, and their tags are listed in the Notes. One other challenge is that sometimes we don’t know exactly which population a dead animal was from (e.g., it was found dead on the floor or in a sump), but we have some guesses
based on the animal size and/or where it was located. Not sure the best way to code for
that._
--> This brings up one question: for those animals that are lumped together in a single entry (`#_of_morts` > 1), can we create multiple entries in the db for each individual animal, and can we extract each animal's tag from the `Note` column??

**Comment by edwinthinks** [comment]
Hello @corneliusellen, I can give this shot :)

**Comment by edwinthinks** [comment]
Submitted a PR for this - https://github.com/rubyforgood/abalone/pull/114

I believe it is close to being done but needs some issues addressed that I encountered. Looking forward to getting this merged!
